# Generated by Django 2.2.6 on 2019-12-17 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('brand', models.CharField(choices=[('Dad', 'Daddario'), ('EB', 'Ernie Ball'), ('Fen', 'Fender'), ('Elx', 'Elixar')], default='Dad', max_length=40)),
                ('guitar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Guitar')),
            ],
        ),
    ]
