# Generated by Django 2.2.6 on 2019-12-18 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_restring'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='restring',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='restring',
            name='date',
            field=models.DateField(verbose_name='restring date'),
        ),
    ]
