# Generated by Django 2.2.6 on 2019-12-18 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20191218_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='guitar',
            name='amps',
            field=models.ManyToManyField(to='main_app.Amp'),
        ),
    ]
